### ISSUE TITLE
grader should be able to reasses any problem result, not jsut latest one associated with solution

### ISSUE THREAD

**Issue by ifjorissen** [ifjorissen/vrfy#140]

**Comment by grantal** [comment]
Other Notes for my own future reference:
- When reassessing problem solution, count earliest correct attempt(ie there are 4 total attempts but the second one was right and the system messed up, give the person 9/10 and only record 2 attempts)
- Have marker on the user side to say it has been reassessed
- ability to delete problem results and then reassess
- Also may want to refactor the code to send things to tango so that this and originally submitting don't get out of sync

**Comment by ifjorissen** [comment]
moved to https://github.com/reed-college/vrfy/issues/18
